### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by sdoerner** [PorterAtGoogle/tree-sitter-textproto#2]
Hi. I'm trying to use this grammar in Helix in [this PR](https://github.com/helix-editor/helix/pull/11874). The reviewer brought up that there is no full License file in this project.

I see that it mentions ISC in [package.json](https://github.com/PorterAtGoogle/tree-sitter-textproto/blob/main/package.json), but would you mind adding a full `LICENSE` file? I would send a PR, but I'm not sure what you want the Copyright line to look like.

**Comment by PorterAtGoogle** [comment]
Done

**Comment by sdoerner** [comment]
Great, thank you for the quick fix!
